;iniCopy code
[pytest]
markers =
 smoke: Run smoke tests
 regression: Run regression tests
 hailey: 这是对标签的解释
 func: custom function
;--disable-warnings
addopts = -v -s --disable-warnings --capture=tee-sys
python_files = test*.py name_*.py
python_class = Test* test*
python_functions = t_* test* test_*  get_*
testpaths = ./script/test
log_cli =True
;color = yes
filterwarnings =
;  error
;  ignore::PytestConfigWarning
;pulgins =
;  pytest-parallel==0.0.10